The PTM represents the action of a quantum channel in the Pauli basis. 
For each pair of Pauli operators $P_i$ and $P_j$, we apply the 
unitary transformation $U P_j U^\dagger$ to $P_j$, and compute 
the Hilbert-Schmidt inner product with $P_i$. The result is 
normalized by $1/2^n$, where $n$ is the number of qubits.

The 2-qubit Pauli matrices are formed by taking the Kronecker (tensor) product of the 1-qubit Pauli matrices (I, X, Y, Z) with themselves and each other. For two qubits, there are 16 such matrices, corresponding to all combinations of two 1-qubit Pauli operators.



In [1]:
import numpy as np

from pauli_transfer_matrix import pauli_transfer_matrix

# Example usage
U_1q = np.array([[ 0.74393664+0.11873822j, -0.37249816-0.54194523j],
       [ 0.41688735+0.50859065j, -0.09296323+0.74759503j]])
U_2q = np.array([[-0.11767162-0.66610803j, -0.3123073 +0.12156049j,
        -0.19688608-0.05984515j,  0.55434302-0.28372332j],
       [ 0.21067037-0.45738353j,  0.22849074+0.12435353j,
        -0.35682263+0.61688169j, -0.35615918+0.20983733j],
       [-0.30887639-0.34714427j, -0.30760334+0.09708465j,
        -0.00061556-0.4971143j , -0.5355084 +0.38229403j],
       [-0.23451941+0.13400989j, -0.39269981-0.7495045j ,
        -0.39803766+0.21031413j, -0.08358532-0.0376742j ]])

# 1-qubit Pauli Transfer Matrix
ptm_1q = pauli_transfer_matrix(U_1q)
print("1-Qubit Pauli Transfer Matrix:")
print(ptm_1q)

# 2-qubit Pauli Transfer Matrix
ptm_2q = pauli_transfer_matrix(U_2q)
print("\n2-Qubit Pauli Transfer Matrix:")
print(ptm_2q)


1-Qubit Pauli Transfer Matrix:
[[ 1.00000000e+00  6.13805601e-09  4.49688198e-09 -7.27584631e-10]
 [-5.45040308e-09 -4.11308697e-01 -5.30720594e-01  7.41053851e-01]
 [ 5.25286129e-09  6.03682653e-01  4.50527398e-01  6.57717510e-01]
 [-1.06189124e-09 -6.82929289e-01  7.17886286e-01  1.35080978e-01]]

2-Qubit Pauli Transfer Matrix:
[[ 9.99999996e-01  2.88423049e-10 -9.59893928e-10 -2.66829100e-09
  -7.18012705e-10  4.96205087e-09 -2.78490669e-09  2.56599374e-09
   3.97823025e-09 -6.15461015e-11  5.39136411e-09 -2.54622157e-10
  -6.97088630e-10  7.46175371e-10 -2.64880221e-09 -3.59054630e-09]
 [ 4.39781724e-09  1.16295547e-01  1.25229144e-01  2.34824543e-01
  -1.12815415e-01  5.07044501e-01  6.68310999e-02 -2.86751194e-01
   5.93597376e-01  3.65974605e-02  1.42640772e-01 -9.41933198e-02
   2.97581198e-01  1.19222182e-01 -2.59195168e-01  7.91815772e-02]
 [-3.18660756e-09  2.53819819e-01  2.31811459e-01 -2.69463466e-01
   7.76526423e-02 -4.18045525e-01 -2.45610556e-01 -6.05067485e-01
  -4.7