In [11]:
import numpy as np

# Define Pauli matrices
I = np.eye(2)
X = np.array([[0, 1], [1, 0]])
Y = np.array([[0, -1j], [1j, 0]])
Z = np.array([[1, 0], [0, -1]])

# Kronecker products for 2-qubit system
pauli_labels = [a+b for a in ['I', 'X', 'Y', 'Z'] for b in ['I', 'X', 'Y', 'Z']]
pauli_matrices = [np.kron(a, b) for a in [I, X, Y, Z] for b in [I, X, Y, Z]]


In [12]:
def decompose_unitary(U):
    """Decompose a 2-qubit unitary matrix into Pauli terms."""
    coeffs = []
    for P in pauli_matrices:
        # Compute the coefficient for each Pauli matrix
        coeff = np.trace(U @ P.conj().T) / 4
        coeffs.append(coeff)
    
    decomposition = {label: coeff for label, coeff in zip(pauli_labels, coeffs)}
    return decomposition

def reconstruct_from_decomposition(decomposition):
    """Reconstruct the unitary matrix from the Pauli term decomposition."""
    return sum(decomposition[label] * P for label, P in zip(pauli_labels, pauli_matrices))


In [13]:
# Example 1: Identity matrix (4x4)
U = np.eye(4)  # 2-qubit identity matrix
print("Original matrix U:")
print(U)

# Decompose and reconstruct
decomposition = decompose_unitary(U)
reconstructed_U = reconstruct_from_decomposition(decomposition)

print("\nDecomposition coefficients:")
for term, coeff in decomposition.items():
    print(f"{term}: {coeff}")

print("\nReconstructed matrix U:")
print(reconstructed_U)

# Check if the original and reconstructed matrices are equal
difference = np.linalg.norm(U - reconstructed_U)
print(f"\nDifference between original and reconstructed matrix: {difference}")


Original matrix U:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

Decomposition coefficients:
II: 1.0
IX: 0.0
IY: 0j
IZ: 0.0
XI: 0.0
XX: 0.0
XY: 0j
XZ: 0.0
YI: 0j
YX: 0j
YY: 0j
YZ: 0j
ZI: 0.0
ZX: 0.0
ZY: 0j
ZZ: 0.0

Reconstructed matrix U:
[[1.+0.j 0.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 1.+0.j 0.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 1.+0.j 0.+0.j]
 [0.+0.j 0.+0.j 0.+0.j 1.+0.j]]

Difference between original and reconstructed matrix: 0.0


In [15]:
# Example 2: Random unitary matrix (4x4)
from scipy.stats import unitary_group
U_random = unitary_group.rvs(4)  # Generate a random 2-qubit unitary

# Decompose and reconstruct the random unitary
decomposition_random = decompose_unitary(U_random)
reconstructed_U_random = reconstruct_from_decomposition(decomposition_random)

print("\nDecomposition coefficients:")
for term, coeff in decomposition_random.items():
    print(f"{term}: {coeff}")

print("\nOriginal random matrix U_random:")
print(U_random)

print("\nReconstructed random matrix U_random:")
print(reconstructed_U_random)

# Check if the original and reconstructed random matrices are equal
difference_random = np.linalg.norm(U_random - reconstructed_U_random)
print(f"\nDifference between original and reconstructed random matrix: {difference_random}")



Decomposition coefficients:
II: (-0.1672404359736122+0.24893515595210114j)
IX: (0.2989227244781403+0.23187715005196563j)
IY: (0.03944617583103629+0.046040558896980346j)
IZ: (-0.25209715661387444-0.10620056862796871j)
XI: (-0.07762370469218106-0.005663421373001867j)
XX: (-0.13719136362545314+0.21011871687707698j)
XY: (-0.04454448018464918-0.20257324381117325j)
XZ: (-0.012191828600234184+0.10615706952914176j)
YI: (-0.21160717906739684+0.20002002814473058j)
YX: (-0.10308340696650323+0.08793035658213207j)
YY: (0.25452343872564115+0.2756806709160024j)
YZ: (0.27144029145746834+0.2736285182108561j)
ZI: (-0.22166715696321748+0.1828273703865052j)
ZX: (0.05378039918205932-0.24432551802187208j)
ZY: (0.039396175660583115-0.01104273228851603j)
ZZ: (0.1334182425332869+0.08867943005062846j)

Original random matrix U_random:
[[-0.50758651+0.41424139j  0.38770095-0.09129072j  0.38383301+0.04066054j
  -0.50635769+0.08206593j]
 [ 0.3177053 +0.06639398j -0.27022868+0.44928366j  0.40783568+0.54433831j
  -